package model.plant;

public enum PlantUpgradeSpecialEffect {
    DOUBLE_SUN_CHANCE,
    TARGET_PRIORITY_UP,
    BUTTER_CHANCE_UP,
    CAN_CRUSH_EXTRA_TARGET,
    MAX_SIZE_UP,
    MELT_AREA,
    EXPLODE_ON_FINISH,
    AOE_ON_DEATH,
    ZOMBIE_HEALTH_BUFF,
    ZOMBIE_DAMAGE_BUFF,
    PLANT_FOOD_ON_PLANTING,
    RESET_FAMILY_COOLDOWNS,
    WARMTH_RADIUS_UP
}
