package model.User;

public enum AccountStatus {
    SUCCESS,
    SECURITY_QUESTION_REQUIRED,
    USERNAME_INVALID,
    USERNAME_TAKEN,
    PASSWORD_INVALID,
    PASSWORD_MISMATCH,
    NICKNAME_INVALID,
    EMAIL_INVALID,
    GENDER_INVALID,
    SECURITY_QUESTION_INVALID,
    SECURITY_ANSWER_INVALID,
    USER_NOT_FOUND,
    CREDENTIALS_INVALID
}
