package model.shop;

public enum ShopActionStatus {

    PURCHASE_SUCCESS,

    INVALID_ITEM,
    INVALID_COUNT,

    USER_NOT_AVAILABLE,
    SHOP_NOT_AVAILABLE,

    NOT_ENOUGH_COINS,
    NOT_ENOUGH_DIAMONDS,

    MAXIMUM_CAPACITY_REACHED,

    PLANT_TYPE_REQUIRED,
    PLANT_NOT_UNLOCKED,
    NO_UNLOCKED_PLANTS,

    DAILY_OFFER_UNAVAILABLE,
    DAILY_OFFER_ALREADY_PURCHASED,
    DAILY_OFFER_INVALID_COUNT,

    VALUE_TOO_LARGE,
    PURCHASE_FAILED
}