package model.Menu;

public enum MenuType {
    SIGNUP_MENU,
    LOGIN_MENU,
    MAIN_MENU,
    GAME_MENU,
    SETTINGS_MENU,
    NETWORK_MENU,
    NEWS_MENU,
    PROFILE_MENU,
    COLLECTION_MENU,
    TRAVEL_LOG_MENU,
    LEADERBOARD_MENU,
    MEOW_POINT_MENU,
    CHAPTER_MENU,
    GREENHOUSE_MENU,
    PLANT_PICK_MENU,
    MID_GAME_MENU
}
