package model.User;

public enum AccountStatus {
    SUCCESS,
    SECURITY_QUESTION_REQUIRED,
    USERNAME_INVALID,
    USERNAME_TAKEN,
    USERNAME_UNCHANGED,
    PASSWORD_INVALID,
    PASSWORD_MISMATCH,
    PASSWORD_UNCHANGED,
    OLD_PASSWORD_INCORRECT,
    NICKNAME_INVALID,
    NICKNAME_UNCHANGED,
    EMAIL_INVALID,
    EMAIL_UNCHANGED,
    GENDER_INVALID,
    SECURITY_QUESTION_INVALID,
    SECURITY_ANSWER_INVALID,
    USER_NOT_FOUND,
    CREDENTIALS_INVALID
}
